parameters:
  - name: TENANT_ID
    displayName: "insert tenant id"
    type: string
  - name: SP_NAME
    displayName: "insert sp name"
    type: string

trigger: none

pool:
  vmImage: ubuntu-latest

variables:
- name: TENANT_ID
  value: ${{parameters.TENANT_ID}}
- name: SP_NAME
  value: ${{parameters.SP_NAME}}

stages:
- stage: RUN_SCRIPT
  displayName: RUN_SCRIPT
  jobs:
  - job: create_sp
    steps:
    - task: AzureCLI@2
      name: run_script
      displayName: run_script
      inputs:
        azureSubscription: 'sc-ava-sub-professional'
        scriptType: 'bash'
        scriptLocation: 'scriptPath'
        scriptPath: 'Azure/create-sp-azure.sh'